### ISSUE TITLE
Language inconsistencies

### ISSUE THREAD

**Issue by nikolay** [mth/yeti#21]
I just discovered Yeti and after the initial euphoria, I face some inconsistencies:

- Why `b_and` and `b_or`, but `xor`? Okay, `xor` is now a term, but what's wrong with using operators `&` and `|`?
- Why `shl` and `shr`? Okay, I remember these abbreviations from my Assembler days, but it's more readable to use `<<<`and `>>>` these days.
- The English-like syntax is killed by made up keywords from archaic languages - `esac`, `elif`, `fi`, etc. Why do you have `do` and `done` instead of `do` and `od` then?! A simple universal block end with `end` or block-specific `end case` are more readable than cryptic abbreviations!
- There's inconsistency in using underscores and capitals - `unsafely_as` and `b_and`, but `classOf`, and `instanceof`. I think the expectation for keywords are letters only and all being lowercase. Of course, `band` will be confusing and that's why many grammars choose `bitand` and `bitor`. I agree that `unsafelyas` is unreadable, maybe `unsafeas` is a bit better, but `unsafe` or `unsafely` could be a modifier of `as` be become `unsafe as` eventually.
- 'norec' is weird! Honestly!

I apologize, I didn't spend much time, I'm sure there are other inconsistencies as well or maybe I'm wrong in my findings, but I just wanted to capture some of my first impressions and maybe they will be of some value to you.

**Comment by mth** [comment]
1. Yeti syntax design has quite strong preference to using keyword operators instead of random symbols. In my opinion it makes code more readable. That's also the reason behind b_and/b_or. The b_ prefix is to distinguish from boolean and/or. There is no boolean xor, so xor isn't prefixed, so yes, this is a bit inconsistent, but not arbitrarily.
2. The shr and shl come from Pascal. As with other cases its preference of keywords to symbolic operators. Maybe some other keywords would have been better, I'm not sure here.
3. Its easier to read code when different kinds of blocks are closed using different keywords - for example matching visually if with elif and fi is very fast and unobstructed by different kinds of nested blocks. The problem of course is that to do it a different ending keywords are needed, or alternatively a more noisy combination like "end if" would have been required. Yeti uses (as usually) already existing syntax from bourne shell as it is familiar to lot of people, for example almost any developer using Linux. The do done also comes from shell, like others. It might be archaic, but it solves the problem.
4. All binary operators are lowercase only. The instanceof is Java operator that does what it does in Java and is written exactly as it is in Java. It would be confusing to different spelling here, as Yeti and Java can often be in same codebase. Yes classOf is exception - it was initially classof, but it just looked weird, so it went into camelcase, like the standard library. You can think of it as being a some kind of special inbuilt function. The "native" (not Java related) operators use quite consistently lower case words and underscore as separator.
5. You should not use norec, almost never. Its only excuse for existance is giving function bindings to inbuilt functions in standard library.
